### ISSUE TITLE
OpenAI Completion Endpoint Params Parity 

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai-api#14]
The completion endpoint on the Python API is currently looking for `max_new_tokens` instead of `max_tokens`. The proposed fix is 2-fold:

1. Make completions and chat completions have body param: `max_tokens` instead of `max_new_tokens`
2. Add error handling for params that do not exist on the Python API (if not already present) and tell the API user

Background: The param max_new_tokens doesn't exist on the OpenAI API ("openai": "^4.14.2") for both [completions](https://platform.openai.com/docs/api-reference/completions/create) and [chat completions](https://platform.openai.com/docs/api-reference/chat/create). It should be max_tokens.

**Comment by justinthelaw** [comment]
@YrrepNoj just wanted to keep this top-of-mind as I think we'd want this fixed before deployment to CENTCOM. It's a simple fix if we need to switch Doug Translate over to `max_new_tokens`, but that would not be on-line with OpenAI spec.

**Comment by YrrepNoj** [comment]
@justinthelaw What errors were you seeing? I thought the endpoints objects were expecting `max_tokens`

**Comment by justinthelaw** [comment]
I may need to test again, but over the weekend when I worked on a code completions request, the `max_tokens` param (I set this to 512 and 1024 to test) didn't change the maximum amount of tokens the LLM produced, leading to a cut-off in the code completion. When I adjusted it to a fetch request using param `max_new_tokens` (I set this to 512 and 1024 to test), it fixed the cut-off.

**Comment by justinthelaw** [comment]
I think the typo is here: https://github.com/defenseunicorns/leapfrogai-api/blob/e2a4a299ad4a0a08fe1b334b51e42b3351a3e57e/backends/openai/routes.py#L37C14-L37C14

In the Go API, the request mapping should be to `max_tokens`
