### ISSUE TITLE
Setup renovate to update the python dependencies

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai-api#18]
We should make sure we are updating our dependencies when possible. Renovate will help keep us aware of downstream updates.

When you set up Renovate, please please please batch all non-major changes. An example config that does that is [here](https://github.com/defenseunicorns/leapfrogai/blob/main/renovate.json).

**Comment by gregclark-defenseunicorns** [comment]
Using dependentbot instead of renovatebot
