### ISSUE TITLE
Container: Run as Non-Root User

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai-api#36]
leapfrogai currently fails the enforced Kyverno policy, run as non-root user. When deployed to a UDS-DUBBD cluster, Kyverno rejects the admission of the leapfrogai-api container into the cluster during deployment. The current workaround it to set the policy to "Audit", else the installation fails.

**Comment by gregclark-defenseunicorns** [comment]
We think we have addressed the issue
