### ISSUE TITLE
Config watch fails to pick-up new backends in k8s cluster

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai-api#37]
https://github.com/defenseunicorns/leapfrogai-api/blob/b50424c36b730b6e8dc011cc9acc935d2cbe64bf/utils/config.py#L43C4-L43C4

I believe the issue is in or around the line of code linked above. I haven't produced this bug before until recently, and it may be another skeleton issue, but it is more likely here.

To reproduce: have leapfrogai API deployed into the cluster first, then upload a backend. Remove the backend and put in a new backend. The new backend is not registered by the API and the old backend is still present on the list of available backends. Restarting the API pod will allow it to re-pickup what is in the cluster.

**Comment by YrrepNoj** [comment]
I believe the new backends are currently picked up by the API but I have noticed the two following conditions:
- Models that are removed from the cluster are not removed from the in-memory dictionary.
- Models that already exist in the dictionary but were redeployed with updated 'backend' location and not being updated in the in-memory dictionary.

**Comment by jalling97** [comment]
Update: I was able to recreate the issue presented this morning. I noticed the following error in the API logs:

```
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Config.watch_and_load_configs() done, defined at /leapfrogai/utils/config.py:30>
exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
    File "/leapfrogai/utils/config.py", line 61, in watch_and_load_configs
    self.load_config_file(os.path.join(directory, match))
    File "/leapfrogai/utils/config.py", line 65, in load_config_file
    with open(config_path) as c:
             ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/config/namespace_leapfrogai.configmap_whisper-configmap.models.toml'  
```
It looks like `load_config_file` is trying to load the config file even when the change registered by awatch is a deletion. I'll look into adding a case for removed config files.
