### ISSUE TITLE
Stop using deprecated `on_event()` decorator.

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai-api#40]
in `main.py` we are using the decorator `@app.on_event('startup')` to start our thread that watches for updates to the config for the LFAI application. This decorator is deprecated and should no longer be used.

Use lifespan event handlers instead. [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).

**Comment by gerred** [comment]
@YrrepNoj Do we want to revisit if we even want to do config reloading? A lot of complexity, but for our deployment targets, we won't be propagating ConfigMap updates (or...are we?)

**Comment by gerred** [comment]
also another thing to tack onto this issue, moving to something like `confz`.

**Comment by YrrepNoj** [comment]
> @YrrepNoj Do we want to revisit if we even want to do config reloading? A lot of complexity, but for our deployment targets, we won't be propagating ConfigMap updates (or...are we?)

I am not opposed to creating a more robust solution for model discovery.

Until we have that though I think this issue should still exist. It _should_ be as simple as swapping a deprecated function call out for a different call.

**Comment by jalling97** [comment]
I addressed this in my working branch for [issue 37](https://github.com/defenseunicorns/leapfrogai-api/issues/37) [here](https://github.com/defenseunicorns/leapfrogai-api/blob/249cd3313e697428a1debab0dbb9f1a5335fb0a3/main.py#L13)

I followed FastAPI's recommendation to swap to a lifespan event handler to deal with the startup and shutdown tasks. I'm happy to include this in my PR for issue 37 or I can roll back on that and make a new one just for this, whichever is preferred.

**Comment by YrrepNoj** [comment]
> I addressed this in my working branch for [issue 37](https://github.com/defenseunicorns/leapfrogai-api/issues/37) [here](https://github.com/defenseunicorns/leapfrogai-api/blob/249cd3313e697428a1debab0dbb9f1a5335fb0a3/main.py#L13)
> 
> I followed FastAPI's recommendation to swap to a lifespan event handler to deal with the startup and shutdown tasks. I'm happy to include this in my PR for issue 37 or I can roll back on that and make a new one just for this, whichever is preferred.

That PR is a perfect place to fix this. Thanks!
