### ISSUE TITLE
Reorganize project code to follow src layout

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai-api#41]
Right now our project uses a `flat layout`. We should update it to follow the `src layout`. This will help us keep our code more organized.
https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/

This is extra useful as it will allow us to better separate the application code from the zarf/k8s/etc configuration.

**Comment by jalling97** [comment]
Started looking at this issue this morning and just wanted to bring up some of the implications of making this change:
- moving everything to an `src` or `app` (as preferred by fastapi) folder I believe will force one of two things:
  - change the import structure to require relative imports on everything (which while I don't mind I know the general philosophy is to avoid relative imports on larger projects)
  - begin treating things not like scripts but as modules, which most likely involves the addition of a `setup.py`, thus moving away from using a `requirements.txt` (and possibly a `setup-dev.py` if we want to keep that paradigm like we do with a separate `requirements-dev.txt`). This also changes how we build and run the API.

I certainly don't mind making these changes if it helps keep things separated I just figured I would bring up these concerns before going further down the rabbit hole.

**Comment by justinthelaw** [comment]
@jalling97 I don't mind implementing best practices for moving away from `requirements-*.txt`, but an example consequence could be breakage of the dependabot paradigm (didn't look into this deeply yet) if we move away from requirements files for those two to look at. Could you provide an example of what you are thinking of implementing?
