### ISSUE TITLE
Ensure API Container runs a non-root-user

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai-api#45]
Migrated from: https://github.com/defenseunicorns/leapfrogai/issues/251

---
The API container seems to fail the kyverno `require-non-root-user` policy. Validate that this is still an issue and update the Dockerfile so that the container is is able to run as a non root user.

**Comment by gregclark-defenseunicorns** [comment]
We think we have addressed the issue
